{{- if .Values.secrets.create }}
---
apiVersion: v1
kind: Secret
metadata:
  name: client-secret-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "federator-suite.labels" . | nindent 4 }}
    app.kubernetes.io/component: client
type: Opaque
stringData:
  client-id: {{ .Values.secrets.idp.clientId | quote }}
  jwks-url: {{ .Values.secrets.idp.jwksUrl | quote }}
  token-url: {{ .Values.secrets.idp.tokenUrl | quote }}
{{- end }}
