{{- if .Values.secrets.create }}
---
apiVersion: v1
kind: Secret
metadata:
  name: federator-client-secret-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "federator-suite.labels" . | nindent 4 }}
    app: federator-client
type: Opaque
data:
  # Connection configuration - empty array by default
  # Format: Base64 encoded JSON array of connection configurations
  connection-configuration.json: {{ (.Values.secrets.clientConfig).connectionConfiguration | default "[\n\n]\n" | b64enc | quote }}
{{- end }}
