{{- if .Values.secrets.create }}
{{- if not .Values.secrets.certificates.external.existingSecrets.clientP12 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: federation-client-p12
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "federator-suite.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if eq .Values.secrets.certificates.source "external" }}
  {{ .Values.secrets.certificates.external.clientP12Filename | default "client.p12" }}: {{ .Values.secrets.certificates.external.clientP12 | default "" }}
  client.p12.password: {{ .Values.secrets.certificates.external.clientP12Password | b64enc }}
  {{- end }}
{{- end }}
{{- end }}
