{{- if .Values.secrets.create }}
{{- if not .Values.secrets.certificates.external.existingSecrets.serverP12 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: federation-server-p12
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "federator-suite.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if eq .Values.secrets.certificates.source "external" }}
  {{ .Values.secrets.certificates.external.serverP12Filename | default "server.p12" }}: {{ .Values.secrets.certificates.external.serverP12 | default "" }}
  server.p12.password: {{ .Values.secrets.certificates.external.serverP12Password | b64enc }}
  {{- end }}
{{- end }}
{{- end }}
