{{- if .Values.secrets.create }}
---
apiVersion: v1
kind: Secret
metadata:
  name: kafka-auth-config
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "federator-suite.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
stringData:
  kafka-auth.properties: {{ printf "security.protocol=%s\nsasl.mechanism=%s\nsasl.jaas.config=%s" (include "federator-suite.kafka.securityProtocol" .) (include "federator-suite.kafka.saslMechanism" .) (.Values.secrets.kafkaAuth.jaasConfig | default "") | quote }}
{{- end }}
