{{- /*
# SPDX-License-Identifier: Apache-2.0
# © Crown Copyright 2025. This work has been developed by the National Digital Twin Programme and is legally attributed to the Department for Business and Trade (UK) as the governing entity.
*/}}

{{- if and .Values.mongodb.secret.create (eq .Values.mongodb.secret.provider "default") -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mongodb.secret.name }}
  {{- with .Values.mongodb.componentSelectorLabels }}
  labels:
    {{- include "ia-node-mongodb.labels" $ | nindent 4 }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.mongodb.secret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  password: {{ .Values.mongodb.secret.password }}
{{- end }}
