{{- /*
# SPDX-License-Identifier: Apache-2.0
# © Crown Copyright 2025. This work has been developed by the National Digital Twin Programme and is legally attributed to the Department for Business and Trade (UK) as the governing entity.
*/}}

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{.Values.mongodb.serviceAccount.name}}
  {{- with .Values.mongodb.componentSelectorLabels }}
  labels:
    {{- include "ia-node-mongodb.labels" $ | nindent 4 }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.mongodb.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}