{{- if and .Values.federatorServer.enabled .Values.federatorServer.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "federator-suite.server.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "federator-suite.server.labels" . | nindent 4 }}
  {{- with .Values.federatorServer.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
