{{- if .Values.federatorClient.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: federator-client-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "federator-suite.client.labels" . | nindent 4 }}
data:
  FEDERATOR_CLIENT_PROPERTIES: /config/client.properties
{{- end }}
