---
apiVersion: v1
kind: ConfigMap
metadata:
  name: common-configuration
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "federator-suite.labels" . | nindent 4 }}
data:
  common-configuration.properties: |
    # SPDX-License-Identifier: Apache-2.0
    # Originally developed by Telicent Ltd.; subsequently adapted, enhanced, and maintained by the National Digital Twin Programme.
    
    # common-configuration.properties
    
    # ============================================
    # Identity Provider (IDP) Configuration
    # ============================================
    
    idp.client.id={{ .Values.secrets.idp.clientId }}
    
    idp.jwks.url={{ .Values.secrets.idp.jwksUrl }}
    
    # Token endpoint URL of the IDP (used to fetch OAuth2 tokens)
    idp.token.url={{ .Values.secrets.idp.tokenUrl }}
    
    # Path to client keystore file (PKCS12 or JKS) used for mutual TLS
    idp.keystore.path={{ .Values.secrets.idp.keystorePath | default "/secrets/federation-cert/client-org1-keystore.jks" }}
    
    # Path to truststore containing the IDP's root CA or certificate chain
    idp.truststore.path=/secrets/federation-cert/keycloak.truststore.jks
    
    idp.mtls.enabled={{ .Values.secrets.idp.mtlsEnabled }}
    
    idp.keystore.password={{ .Values.secrets.idp.keystorePassword }}
    idp.truststore.password={{ .Values.secrets.idp.truststorePassword }}
