
{{- /*
# SPDX-License-Identifier: Apache-2.0
# © Crown Copyright 2025. This work has been developed by the National Digital Twin Programme and is legally attributed to the Department for Business and Trade (UK) as the governing entity.
*/}}

{{- if and .Values.istio.enabled .Values.istio.virtualService.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: kafka
  labels:
    strimzi.io/cluster: {{.Values.kafkaCluster.name}}
  {{- with .Values.istio.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  gateways:
  {{- range .Values.istio.virtualService.gateways }}
    - {{ . }}
  {{- end }}
  hosts:
    {{- toYaml .Values.istio.virtualService.hosts | nindent 4 }}
  tcp:
  - match:
    - port: 9093
    route:
    - destination:
        host: {{ printf "%s-kafka-bootstrap" .Values.kafkaCluster.name }}
        port:
          number: 9093
{{- end }}