{{- /*
# SPDX-License-Identifier: Apache-2.0
# © Crown Copyright 2025. This work has been developed by the National Digital Twin Programme and is legally attributed to the Department for Business and Trade (UK) as the governing entity.
*/}}

{{- if .Values.kafkaCluster.connectEnabled  -}}
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: {{  .Values.kafkaCluster.secret.usernameConnect }}
  labels:
    strimzi.io/cluster: {{.Values.kafkaCluster.name}}
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
    - resource:
        type: group
        name: connect-cluster
      operations:
        - Read
    - resource:
        type: topic
        name: connect-cluster-configs
      operations:
        - Create
        - Describe
        - Read
        - Write
    - resource:
        type: topic
        name: connect-cluster-status
      operations:
        - Create
        - Describe
        - Read
        - Write
    - resource:
        type: topic
        name: connect-cluster-offsets
      operations:
        - Create
        - Describe
        - Read
        - Write
    - resource:
        type: group
        name: connect-cluster
      operations:
       - Read
    - resource:
        type: topic
        name: knowledge
        patternType: literal
      operations:
      - Create
      - Describe
      - Read
      - Write
    - resource:
        type: topic
        name: ontology
        patternType: literal
      operations:
      - Create
      - Describe
      - Read
      - Write
{{- end }}