{{- /*
# SPDX-License-Identifier: Apache-2.0
# © Crown Copyright 2025. This work has been developed by the National Digital Twin Programme and is legally attributed to the Department for Business and Trade (UK) as the governing entity.
*/}}

apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: {{.Values.kafkaCluster.name}}
spec:
  kafka:
    version: {{.Values.kafkaCluster.spec.version}}
    replicas: {{.Values.kafkaCluster.spec.kafkaReplicas}}
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
        authentication:
          type: scram-sha-512
      - name: tls
        port: 9093
        type: internal
        tls: true
        authentication:
          type: scram-sha-512
    authorization:
      type: simple
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
      inter.broker.protocol.version: "3.9"
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 1Gi
        deleteClaim: false
  zookeeper:
    replicas: {{.Values.kafkaCluster.spec.zookeeperReplicas}}
    template:
      pod:
        metadata:
          labels:
            sidecar.istio.io/inject: "false"
    storage:
      type: persistent-claim
      size: 1Gi
      deleteClaim: false
  entityOperator:
    topicOperator: {}
    userOperator: {}