{{- if .Values.serviceMesh.istio.enabled }}
---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: peerauthentication-strict
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "federator-suite.labels" . | nindent 4 }}
spec:
  mtls:
    mode: {{ .Values.serviceMesh.istio.peerAuthentication.mode | default "STRICT" | upper }}
{{- end }}