# SPDX-License-Identifier: Apache-2.0
# © Crown Copyright 2025. This work has been developed by the National Digital Twin Programme and is legally attributed to the Department for Business and Trade (UK) as the governing entity.

istio:
  annotations: {}
  enabled: true
  extraDefaults: false
  principals: 
    - cluster.local/ns/ia-node/sa/access-api
  peerAuthenticationMode: STRICT
  virtualService:
    enabled: false
    hosts:
      - "*"
    gateways:
      - istio-system/istio-gateway 

mongodb:
  annotations: {}
  name: mongodb

  spec:
    members: 3
    version: "6.0.5"
    security:
      tls:
        enabled: false
        useX509: false
        certificateKeySecretRef: tls-certificate
        caCertificateSecretRef: tls-ca-key-pair
  
  componentSelectorLabels:
    app: mongodb-svc

  secret:
    create: true
    name: "ia-node-user-password" 
    providerClassEnabled: false
    provider: default
    objectName: default
    objectType: default
    password: supersecretpassword
    annotations: {}

  users:
    default:
      name: ia-node-user
      db: access
      roles:
        - clusterAdmin
        - userAdminAnyDatabase
        - backup
        - dbAdminAnyDatabase
        - restore
        - MongodbAutomationAgentUserRole
        - readWriteAnyDatabase
        - enableSharding
        - dbOwner

  serviceAccount:
    annotations: {}
    name: mongodb-database

  role:
    annotations: {}
    name: role-mongodb-database

  roleBinding:
    annotations: {}
    name: mongodb-database-binding