apiVersion: v1
kind: Service
metadata:
  name: {{ include "management-node.fullname" . }}
  labels:
    helm.sh/chart: {{ include "management-node.chart" . }}
    app.kubernetes.io/name: {{ include "management-node.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/managed-by: Helm
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "management-node.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: https
      port: {{ .Values.service.port }}
      targetPort: https
    - name: http
      port: {{ .Values.app.management.port }}
      targetPort: {{ .Values.app.management.port }}
      protocol: TCP
