{{- if and .Values.valkeyUi.enabled (eq .Values.valkeyUi.image.repository "redis/redisinsight") }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: valkey-ui-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: valkey-ui
    {{ include "federator-suite.labels" . | nindent 4 }}
data:
  databases.json: |
    [
      {
        "host": "{{ include "federator-suite.valkey.host" . }}",
        "port": {{ include "federator-suite.valkey.port" . }},
        "name": "BCC Valkey",
        {{- if .Values.valkey.external }}
          {{- if .Values.valkey.externalConfig.auth.enabled }}
        "password": "{{ .Values.valkey.externalConfig.auth.token }}",
          {{- end }}
          {{- if .Values.valkey.externalConfig.tls.enabled }}
        "tls": true,
          {{- else }}
        "tls": false,
          {{- end }}
        {{- else }}
          {{- if .Values.valkey.valkey.auth.enabled }}
        "password": "{{ .Values.valkey.valkey.auth.password }}",
          {{- end }}
        "tls": false,
        {{- end }}
        "db": 0
      }
    ]
{{- end }}
