{{- if .Values.valkeyUi.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: valkey-ui
  namespace: {{ .Release.Namespace }}
  labels:
    app: valkey-ui
    {{ include "federator-suite.labels" . | nindent 4 }}
  {{- with .Values.valkeyUi.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.valkeyUi.service.type }}
  {{- if and (eq .Values.valkeyUi.service.type "NodePort") .Values.valkeyUi.service.nodePort }}
  ports:
  - port: 5540
    targetPort: http
    protocol: TCP
    name: http
    nodePort: {{ .Values.valkeyUi.service.nodePort }}
  {{- else }}
  ports:
  - port: 5540
    targetPort: http
    protocol: TCP
    name: http
  {{- end }}
  selector:
    app: valkey-ui
{{- end }}
