{{- /*
# SPDX-License-Identifier: Apache-2.0
# © Crown Copyright 2025. This work has been developed by the National Digital Twin Programme and is legally attributed to the Department for Business and Trade (UK) as the governing entity.
*/}}

{{- if and .Values.istio.enabled .Values.istio.extraDefaults -}}
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: peerauthentication-strict
  labels:
    {{- include "ia-node.labels" $ | nindent 4 }}
    {{- with .Values.istio.annotations }}
    annotations:
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  mtls:
    mode: {{.Values.istio.peerAuthenticationMode }} 
{{- end }}