{{- /*
# SPDX-License-Identifier: Apache-2.0
# © Crown Copyright 2025. This work has been developed by the National Digital Twin Programme and is legally attributed to the Department for Business and Trade (UK) as the governing entity.
*/}}

{{- if .Values.oidcProvider.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.oidcProvider.secret.name }}
  {{- with .Values.oidcProvider.componentSelectorLabels }}
  labels:
    {{- include "ia-node-oidc.labels" $ | nindent 4 }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.oidcProvider.secret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  cookie-secret: {{ .Values.oidcProvider.secret.cookieSecret }}
  client-secret: {{ .Values.oidcProvider.secret.clientSecret }}
  client-id: {{ .Values.oidcProvider.secret.clientId }}
{{- end }}