{{- /*
# SPDX-License-Identifier: Apache-2.0
# © Crown Copyright 2025. This work has been developed by the National Digital Twin Programme and is legally attributed to the Department for Business and Trade (UK) as the governing entity.
*/}}

{{- if .Values.istio.enabled -}}
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: oauth2-proxy-to-apps
  {{- with .Values.oAuth2Proxy.componentSelectorLabels }}
  labels:
  {{- include "ia-node-oidc.labels" $ | nindent 4 }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with.Values.istio.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- toYaml .Values.oAuth2Proxy.componentSelectorLabels | nindent 6 }}
  action: ALLOW
  rules:
  - from:
    - source:
        principals:
        - {{.Values.istio.principal}}
    to:
    - operation:
        methods:
        - GET
        - POST
        - HEAD
        - DELETE
        - PUT
        - PATCH
{{- end }}
