{{- /*
# SPDX-License-Identifier: Apache-2.0
# © Crown Copyright 2025. This work has been developed by the National Digital Twin Programme and is legally attributed to the Department for Business and Trade (UK) as the governing entity.
*/}}

{{- if .Values.oidcProvider.configMap.create -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.oidcProvider.configMap.name }}
  {{- with .Values.oAuth2Proxy.componentSelectorLabels }}
  labels:
    {{- include "ia-node-oidc.labels" $ | nindent 4 }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.oidcProvider.configMap.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  {{- if contains .Values.oidcProvider.type "keycloak" }} 
  oauth2_proxy.cfg: |-
    {{- tpl ($.Files.Get "config/oauth2-proxy-keycloak.cfg") . | nindent 4 }}
  {{ else }}
  oauth2_proxy.cfg: |-
    {{- tpl ($.Files.Get "config/oauth2-proxy-default.cfg") . | nindent 4 }}
  {{- end }}
{{- end }}