{{- /*
# SPDX-License-Identifier: Apache-2.0
# © Crown Copyright 2025. This work has been developed by the National Digital Twin Programme and is legally attributed to the Department for Business and Trade (UK) as the governing entity.
*/}}

{{- if and .Values.istio.enabled .Values.apps.query.enabled -}}
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: allow-ingress-to-query-ui
  labels:
    {{- include "ia-node.labels" $ | nindent 4 }}
    {{- toYaml .Values.apps.query.componentSelectorLabels | nindent 4 }}
spec:
  action: ALLOW
  rules:
    - from:
        - source:
            principals:
              - {{.Values.istio.principal}}
      to:
        - operation:
            methods:  
              - GET
  selector:
    matchLabels:
      {{- toYaml .Values.apps.query.componentSelectorLabels | nindent 6 }}
{{- end }}