{{- /*
# SPDX-License-Identifier: Apache-2.0
# © Crown Copyright 2025. This work has been developed by the National Digital Twin Programme and is legally attributed to the Department for Business and Trade (UK) as the governing entity.
*/}}

{{- if and .Values.istio.enabled .Values.apps.api.enabled -}}
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: allow-ingress-access-to-api
  labels:
    {{- include "ia-node.labels" $ | nindent 4 }}
    {{- toYaml .Values.apps.api.componentSelectorLabels | nindent 4 }}
spec:
  action: ALLOW
  rules:
    - from:
        - source:
            principals:
              - {{.Values.istio.principal}}
      to:
        - operation:
            methods:
              - GET
              - POST
              - DELETE
              - PUT
              - PATCH
      # when:
      #   - key: 'request.auth.claims[groups]'
      #     values:
      #       - {{.Values.istio.groupClaimNames.admin }}
    - from:
        - source:
            principals:
              - {{.Values.istio.principal}}
      to:
        - operation:
            methods:
              - GET
            paths:
              - /api/access/whoami
      when:
        - key: 'request.auth.claims[groups]'
          values:
            - {{.Values.istio.groupClaimNames.read }}
  selector:
    matchLabels:
      {{- toYaml .Values.apps.api.componentSelectorLabels | nindent 6 }}
{{- end }}

