{{- /*
# SPDX-License-Identifier: Apache-2.0
# © Crown Copyright 2025. This work has been developed by the National Digital Twin Programme and is legally attributed to the Department for Business and Trade (UK) as the governing entity.
*/}}

{{- range .Values.apps }}
--- 
{{- if and .enabled .statefulSet }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .name }}
  {{- with .componentSelectorLabels }}
  labels:
    {{- include "ia-node.labels" $ | nindent 4 }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .statefulSet.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .statefulSet.replicas }}
  revisionHistoryLimit: 3
  selector:
    {{- with .componentSelectorLabels }}  
    matchLabels:
      {{- include "ia-node.selectorLabels" $ | nindent 6 }}
      {{- toYaml . | nindent 6 }}
    {{- end }}
  template:
    metadata:
       {{- with .statefulSet.templateAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .componentSelectorLabels }}  
      labels:
        {{- include "ia-node.selectorLabels" $ | nindent 8 }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      containers:
      - name: {{ .name }}
        image: "{{ .statefulSet.image.repository }}:{{ .statefulSet.image.tag }}"
        imagePullPolicy: Always
        ports:
        - containerPort: 3030
          name: http
          protocol: TCP
        - containerPort: 9090
          name: metrics
          protocol: TCP
        resources:
          {{- toYaml .statefulSet.resources | nindent 10 }}
        livenessProbe:
          {{- toYaml .statefulSet.livenessProbe | nindent 10 }}
        readinessProbe:
          {{- toYaml .statefulSet.readinessProbe | nindent 10 }}
        env:
          {{- with .statefulSet.env }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
          {{- if $.Values.extraCerts.required }}
          - name: NODE_EXTRA_CA_CERTS
            value: /etc/ssl/certs/{{ $.Values.extraCerts.name }}
          {{- end }}
        envFrom:
          {{- toYaml .statefulSet.envFrom | nindent 10 }}
        args:
          {{- with .statefulSet.args }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsGroup: 10101
          runAsNonRoot: true
          runAsUser: 10101
          seccompProfile:
            type: RuntimeDefault
        volumeMounts: 
          {{- with .statefulSet.volumeMounts }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
          {{- if $.Values.extraCerts.required }}
          - name: {{ $.Values.extraCerts.configMapRef }}
            mountPath: "/etc/ssl/certs/{{ $.Values.extraCerts.name }}"
            subPath: {{ $.Values.extraCerts.name }}
          {{- end }}
      {{- with $.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        fsGroup: 185
        runAsGroup: 185
        runAsNonRoot: true
        runAsUser: 185
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: {{ .name }}
      volumes: 
        {{- with .statefulSet.volumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if $.Values.extraCerts.required }}
        - name: {{ $.Values.extraCerts.configMapRef }}
          configMap:
            name: {{ $.Values.extraCerts.configMapRef }}
        {{- end }}
  volumeClaimTemplates:
  - metadata:
      {{- with .componentSelectorLabels }}  
      labels:
        {{- include "ia-node.selectorLabels" $ | nindent 8 }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      name: graph-data-volume
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 100Gi
  - metadata:
      {{- with .componentSelectorLabels }}  
      labels:
        {{- include "ia-node.selectorLabels" $ | nindent 8 }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      name: graph-label-volume
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 100Gi
{{- end }}
{{- end }}