{{- /*
# SPDX-License-Identifier: Apache-2.0
# © Crown Copyright 2025. This work has been developed by the National Digital Twin Programme and is legally attributed to the Department for Business and Trade (UK) as the governing entity.
*/}}

{{- if .Values.kafkaCluster.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.kafkaCluster.secret.name }}
  {{- with .Values.kafkaCluster.componentSelectorLabels }}
  labels:
    {{- include "ia-node.labels" $ | nindent 4 }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.kafkaCluster.secret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  kafka-config.properties: |
    security.protocol=SASL_SSL
    sasl.mechanism=SCRAM-SHA-512
    sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required \
        username="{{.Values.kafkaCluster.secret.username }}" \
        password="{{.Values.kafkaCluster.secret.password }}";
{{- end }}