{{- if .Values.vault.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "federator-suite.vault.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "federator-suite.labels" . | nindent 4 }}
    app.kubernetes.io/component: vault
  {{- if .Values.vault.serviceAccount.annotations }}
  annotations:
    {{- toYaml .Values.vault.serviceAccount.annotations | nindent 4 }}
  {{- end }}
{{- end }}
